### ISSUE TITLE
Question: Inserting Duplicates

### ISSUE THREAD

**Issue by visenger** [dbunibas/BART#4]
Hi,
as I understood, there are several strategies to make the data set dirty: 

1. TypoAppendString
2. TypoAddString
3. TypoRandom
4. TypoRemoveString
5. TypoSwitchValue
6. TypoActiveDomain
and outlierErrors

How should I configure an EG Task (.xml file) in order to insert duplicates into my data?
May be you have an example for me?

Thank you in advance for your help!

**Comment by donatellosantoro** [comment]
Hi visenger,
what do you mean by duplicates? 
Given a database and a set of dependencies, BART is able to introduce detectable violations w.r.t. these constraints changing the values of a set of cells. It will never introduce new or duplicate tuples.

**Comment by visenger** [comment]
Hi @donatellosantoro Donatello, 

from your [paper](https://docs.google.com/viewer?url=http%3A%2F%2Fdb.unibas.it%2Fprojects%2Fbart%2Ffiles%2FTR-01-2015.pdf):

> Use-Case 2: Generate Random Errors. In addition to detectable errors, Bart may also generate random errors of several kinds: typos (e.g., ‘databse’),duplicated values, bogus or null values (e.g., ‘999’, ‘***’), ...

What settings in BART introduces such duplicated values?

Thank you for your help.

**Comment by donatellosantoro** [comment]
Duplicated values means that BART will change the value of a cell by using another value from active domain.

Example  
given a  functional dependency 
```
// FD: Zip -> City
e1: person(ssn: $ssn1, name: $n1, surname: $s1, city: $c1, zip: $z1), 
person(ssn: $ssn2, name: $n2, surname: $s2, city: $c2, zip: $z2), 
    $z1 == $z2, $c1 != $c2 -> #fail.
```

and a clean database
```
tid, ssn, name, surname, city, zip (integer)
t1, 123, Jon, Snow, The Wall, 100
t2, 123, Jon, Snow, Winterfell, 101
t3, 345, Ed, Stark, Winterfell, 101
```

a detectable change for the viogen query
```
<vioGenQuery id="e1">
    <comparison>(c1 != c2)</comparison>
    <percentage>1.0</percentage> 
</vioGenQuery>
```
with dirty strategy  `TypoActiveDomain`
```
<dirtyStrategies>
            <defaultStrategy>
                <strategy chars="*" charsToAdd="3">TypoAddString</strategy>
            </defaultStrategy> 
            <attributeStrategy>
                <attribute table="person" name="city">
                    <strategy>TypoActiveDomain</strategy>
                </attribute>
            </attributeStrategy>
</dirtyStrategies>
```

may generate the change `3.city: Winterfell -> The Wall`

**Comment by visenger** [comment]
Great example! Thank you @donatellosantoro  ! This was helpful
